name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "Android/**"
  pull_request:
    branches: ["main"]
    paths:
      - "Android/**"

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Android/src

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Install Android SDK Platform 37
        run: |
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "platforms;android-37"

      - name: Build
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mobile-Actions-APK
          path: Android/src/app/build/outputs/apk/release/*.apk
